/**
 * Blog content architecture — Phase 8 SEO roadmap
 * 40 articles across 4 categories. Do not write articles yet; use this as the editorial calendar.
 */

export interface BlogPlan {
  slug: string
  title: string
  category: string
  primaryKeyword: string
  secondaryKeywords: string[]
  estimatedSearchVolume: 'high' | 'medium' | 'low'
  priority: number // 1 = publish first
}

export const BLOG_ROADMAP: BlogPlan[] = [
  // ── ONLINE STUDY ROOMS (10) ──────────────────────────────────────────
  {
    slug: 'best-online-study-rooms-free',
    title: 'The 7 Best Free Online Study Rooms in 2025',
    category: 'Online Study Rooms',
    primaryKeyword: 'online study room free',
    secondaryKeywords: ['virtual study room', 'study with me online', 'study room website'],
    estimatedSearchVolume: 'high',
    priority: 1,
  },
  {
    slug: 'how-to-create-virtual-study-room',
    title: 'How to Create Your Own Virtual Study Room (Step-by-Step)',
    category: 'Online Study Rooms',
    primaryKeyword: 'virtual study room',
    secondaryKeywords: ['online study space', 'study setup at home', 'digital study room'],
    estimatedSearchVolume: 'high',
    priority: 2,
  },
  {
    slug: 'study-with-me-online-benefits',
    title: 'Why Studying Online with Others Makes You More Productive',
    category: 'Online Study Rooms',
    primaryKeyword: 'study with me online',
    secondaryKeywords: ['virtual study group', 'body doubling', 'accountability partner'],
    estimatedSearchVolume: 'high',
    priority: 3,
  },
  {
    slug: 'anime-study-room-setup-guide',
    title: 'Anime Study Room: Complete Setup Guide for 2025',
    category: 'Online Study Rooms',
    primaryKeyword: 'anime study room',
    secondaryKeywords: ['aesthetic study room', 'japanese study space', 'lofi anime study'],
    estimatedSearchVolume: 'high',
    priority: 4,
  },
  {
    slug: 'notion-study-room-setup',
    title: 'How to Turn Notion into a Study Room (with Lofi Widget)',
    category: 'Online Study Rooms',
    primaryKeyword: 'notion study room',
    secondaryKeywords: ['notion workspace aesthetic', 'notion embed lofi', 'notion productivity'],
    estimatedSearchVolume: 'medium',
    priority: 5,
  },
  {
    slug: 'coding-room-setup-developers',
    title: 'The Perfect Coding Room Setup for Developers in 2025',
    category: 'Online Study Rooms',
    primaryKeyword: 'coding room',
    secondaryKeywords: ['developer workspace', 'programming setup', 'coding environment'],
    estimatedSearchVolume: 'medium',
    priority: 6,
  },
  {
    slug: 'deep-work-room-guide',
    title: 'Deep Work Room: How to Build a Distraction-Free Workspace',
    category: 'Online Study Rooms',
    primaryKeyword: 'deep work room',
    secondaryKeywords: ['deep work setup', 'focus environment', 'cal newport deep work'],
    estimatedSearchVolume: 'medium',
    priority: 7,
  },
  {
    slug: 'study-room-sounds-comparison',
    title: 'Rain vs Café vs Library: Which Study Sound is Best?',
    category: 'Online Study Rooms',
    primaryKeyword: 'best sound for studying',
    secondaryKeywords: ['study ambient sounds', 'white noise studying', 'rain sounds study'],
    estimatedSearchVolume: 'medium',
    priority: 8,
  },
  {
    slug: 'embed-study-room-notion-blog',
    title: 'How to Embed a Study Room in Notion, Blog or Any Website',
    category: 'Online Study Rooms',
    primaryKeyword: 'embed study room notion',
    secondaryKeywords: ['iframe notion', 'notion embed widget', 'lofi widget embed'],
    estimatedSearchVolume: 'low',
    priority: 9,
  },
  {
    slug: 'study-room-with-friends-online',
    title: 'How to Study with Friends Online (Virtual Study Sessions)',
    category: 'Online Study Rooms',
    primaryKeyword: 'study with friends online',
    secondaryKeywords: ['virtual study group', 'online study partner', 'body doubling'],
    estimatedSearchVolume: 'medium',
    priority: 10,
  },

  // ── PRODUCTIVITY (10) ─────────────────────────────────────────────────
  {
    slug: 'pomodoro-vs-time-blocking',
    title: 'Pomodoro vs Time Blocking: Which Method Actually Works?',
    category: 'Productivity',
    primaryKeyword: 'pomodoro vs time blocking',
    secondaryKeywords: ['time management techniques', 'focus method', 'productivity system'],
    estimatedSearchVolume: 'high',
    priority: 1,
  },
  {
    slug: 'deep-work-beginner-guide',
    title: "Cal Newport's Deep Work: Beginner's Guide to Focused Work",
    category: 'Productivity',
    primaryKeyword: 'deep work beginner guide',
    secondaryKeywords: ['cal newport deep work', 'focused work sessions', 'flow state'],
    estimatedSearchVolume: 'high',
    priority: 2,
  },
  {
    slug: 'ambient-sound-productivity-science',
    title: 'The Science of Ambient Sound and Productivity (Research-Backed)',
    category: 'Productivity',
    primaryKeyword: 'ambient sound productivity',
    secondaryKeywords: ['white noise productivity', 'music while working', 'sound concentration'],
    estimatedSearchVolume: 'medium',
    priority: 3,
  },
  {
    slug: 'flow-state-how-to-achieve',
    title: 'How to Achieve Flow State: 7 Evidence-Based Techniques',
    category: 'Productivity',
    primaryKeyword: 'how to achieve flow state',
    secondaryKeywords: ['flow state work', 'deep focus technique', 'csikszentmihalyi flow'],
    estimatedSearchVolume: 'high',
    priority: 4,
  },
  {
    slug: 'study-streak-motivation',
    title: 'How Daily Study Streaks Changed My Productivity (And How to Build One)',
    category: 'Productivity',
    primaryKeyword: 'study streak',
    secondaryKeywords: ['habit streak', 'daily study habit', 'consistency motivation'],
    estimatedSearchVolume: 'low',
    priority: 5,
  },
  {
    slug: 'best-productivity-apps-students-2025',
    title: 'Best Productivity Apps for Students in 2025 (Free & Paid)',
    category: 'Productivity',
    primaryKeyword: 'best productivity apps students',
    secondaryKeywords: ['study apps', 'student productivity tools', 'focus apps'],
    estimatedSearchVolume: 'high',
    priority: 6,
  },
  {
    slug: 'distraction-free-workspace-setup',
    title: 'How to Set Up a Distraction-Free Workspace (Digital & Physical)',
    category: 'Productivity',
    primaryKeyword: 'distraction free workspace',
    secondaryKeywords: ['focus workspace setup', 'minimize distractions', 'deep work environment'],
    estimatedSearchVolume: 'medium',
    priority: 7,
  },
  {
    slug: 'gamification-studying-xp-system',
    title: 'How Gamifying Your Studies with XP and Streaks Boosts Motivation',
    category: 'Productivity',
    primaryKeyword: 'gamification studying',
    secondaryKeywords: ['xp study system', 'study rewards', 'gamify learning'],
    estimatedSearchVolume: 'medium',
    priority: 8,
  },
  {
    slug: 'morning-study-routine',
    title: 'The Ultimate Morning Study Routine for Maximum Productivity',
    category: 'Productivity',
    primaryKeyword: 'morning study routine',
    secondaryKeywords: ['study morning routine', 'productive morning', 'early study habit'],
    estimatedSearchVolume: 'high',
    priority: 9,
  },
  {
    slug: 'todo-list-vs-calendar-productivity',
    title: 'To-Do List vs Calendar: Which Should You Use for Studying?',
    category: 'Productivity',
    primaryKeyword: 'todo list vs calendar',
    secondaryKeywords: ['task management', 'study planning', 'calendar studying'],
    estimatedSearchVolume: 'medium',
    priority: 10,
  },

  // ── POMODORO (10) ─────────────────────────────────────────────────────
  {
    slug: 'pomodoro-technique-complete-guide',
    title: 'The Pomodoro Technique: Complete Guide for Students (2025)',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro technique guide',
    secondaryKeywords: ['how to use pomodoro', 'pomodoro for students', 'pomodoro technique steps'],
    estimatedSearchVolume: 'high',
    priority: 1,
  },
  {
    slug: 'pomodoro-timer-online-free',
    title: 'Best Free Online Pomodoro Timers in 2025 (Compared)',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro timer online free',
    secondaryKeywords: ['online pomodoro', 'free pomodoro timer', 'pomodoro app'],
    estimatedSearchVolume: 'high',
    priority: 2,
  },
  {
    slug: 'pomodoro-25-minutes-why',
    title: 'Why 25 Minutes? The Science Behind the Pomodoro Interval',
    category: 'Pomodoro',
    primaryKeyword: 'why 25 minutes pomodoro',
    secondaryKeywords: ['pomodoro interval', 'focus duration science', 'attention span'],
    estimatedSearchVolume: 'medium',
    priority: 3,
  },
  {
    slug: 'pomodoro-with-lofi-music',
    title: 'Pomodoro + Lofi Music: The Ultimate Study Combination',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro with lofi music',
    secondaryKeywords: ['lofi pomodoro', 'study music pomodoro', 'focus music timer'],
    estimatedSearchVolume: 'medium',
    priority: 4,
  },
  {
    slug: 'pomodoro-breaks-what-to-do',
    title: 'What to Do During Pomodoro Breaks (5 Productive Options)',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro break activities',
    secondaryKeywords: ['pomodoro 5 minute break', 'rest between sessions', 'break productivity'],
    estimatedSearchVolume: 'medium',
    priority: 5,
  },
  {
    slug: 'pomodoro-vs-52-17-rule',
    title: 'Pomodoro 25/5 vs 52/17 Rule: Which Interval is Best for You?',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro vs 52 17 rule',
    secondaryKeywords: ['best focus interval', '52 17 rule productivity', 'focus break ratio'],
    estimatedSearchVolume: 'medium',
    priority: 6,
  },
  {
    slug: 'pomodoro-coding-sessions',
    title: 'Pomodoro for Coding: How to Structure Your Programming Sessions',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro coding',
    secondaryKeywords: ['programming pomodoro', 'coding focus sessions', 'developer pomodoro'],
    estimatedSearchVolume: 'medium',
    priority: 7,
  },
  {
    slug: 'pomodoro-xp-gamification',
    title: 'Gamify Your Pomodoro Sessions with XP and Level-Ups',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro gamification xp',
    secondaryKeywords: ['gamified pomodoro', 'xp pomodoro app', 'reward system studying'],
    estimatedSearchVolume: 'low',
    priority: 8,
  },
  {
    slug: 'pomodoro-long-study-sessions',
    title: 'How to Stay Focused During 4+ Hour Study Sessions with Pomodoro',
    category: 'Pomodoro',
    primaryKeyword: 'long study sessions pomodoro',
    secondaryKeywords: ['extended focus sessions', 'marathon study', 'all day studying'],
    estimatedSearchVolume: 'medium',
    priority: 9,
  },
  {
    slug: 'pomodoro-streak-building',
    title: 'How to Build a 30-Day Pomodoro Streak (With Templates)',
    category: 'Pomodoro',
    primaryKeyword: 'pomodoro streak',
    secondaryKeywords: ['30 day study challenge', 'pomodoro habit', 'study consistency'],
    estimatedSearchVolume: 'low',
    priority: 10,
  },

  // ── ANIME STUDY SETUPS (10) ───────────────────────────────────────────
  {
    slug: 'anime-study-setup-guide-2025',
    title: 'Anime Study Setup: How to Create the Ultimate Aesthetic Workspace',
    category: 'Anime Study Setups',
    primaryKeyword: 'anime study setup',
    secondaryKeywords: ['aesthetic study setup', 'japanese workspace', 'cozy study aesthetic'],
    estimatedSearchVolume: 'high',
    priority: 1,
  },
  {
    slug: 'lofi-girl-aesthetic-workspace',
    title: 'Recreate the Lofi Girl Aesthetic in Your Own Study Space',
    category: 'Anime Study Setups',
    primaryKeyword: 'lofi girl aesthetic workspace',
    secondaryKeywords: ['lofi girl setup', 'cozy study room aesthetic', 'rainy window study'],
    estimatedSearchVolume: 'high',
    priority: 2,
  },
  {
    slug: 'best-lofi-music-anime-studying',
    title: 'Best Lofi Music for Studying — Japanese & Anime Inspired Playlists',
    category: 'Anime Study Setups',
    primaryKeyword: 'lofi music anime studying',
    secondaryKeywords: ['japanese lofi study', 'anime lofi playlist', 'city pop studying'],
    estimatedSearchVolume: 'high',
    priority: 3,
  },
  {
    slug: 'studio-ghibli-study-atmosphere',
    title: 'How to Create a Studio Ghibli Study Atmosphere at Home',
    category: 'Anime Study Setups',
    primaryKeyword: 'studio ghibli study atmosphere',
    secondaryKeywords: ['ghibli aesthetic room', 'hayao miyazaki inspired', 'totoro study room'],
    estimatedSearchVolume: 'medium',
    priority: 4,
  },
  {
    slug: 'vtuber-study-with-me',
    title: 'VTuber Study With Me: Why Virtual Study Partners Work',
    category: 'Anime Study Setups',
    primaryKeyword: 'vtuber study with me',
    secondaryKeywords: ['virtual study partner', 'study with vtuber', 'hololive study'],
    estimatedSearchVolume: 'medium',
    priority: 5,
  },
  {
    slug: 'rain-study-aesthetic-background',
    title: 'Rainy Day Study Aesthetic: Backgrounds, Sounds & Setup Guide',
    category: 'Anime Study Setups',
    primaryKeyword: 'rain study aesthetic',
    secondaryKeywords: ['rainy study background', 'rain study sounds', 'aesthetic study gif'],
    estimatedSearchVolume: 'medium',
    priority: 6,
  },
  {
    slug: 'cozy-study-room-aesthetic-tips',
    title: '10 Ways to Make Your Study Room Look Cozy and Aesthetic',
    category: 'Anime Study Setups',
    primaryKeyword: 'cozy study room aesthetic',
    secondaryKeywords: ['aesthetic study space', 'cute study room', 'cozy desk setup'],
    estimatedSearchVolume: 'high',
    priority: 7,
  },
  {
    slug: 'japanese-city-pop-study-music',
    title: 'Japanese City Pop for Studying: The Complete Guide',
    category: 'Anime Study Setups',
    primaryKeyword: 'japanese city pop studying',
    secondaryKeywords: ['city pop music study', 'japanese music focus', '80s city pop lofi'],
    estimatedSearchVolume: 'medium',
    priority: 8,
  },
  {
    slug: 'gif-background-study-room',
    title: 'Animated GIF Study Backgrounds: Best Sources and How to Use Them',
    category: 'Anime Study Setups',
    primaryKeyword: 'gif study background',
    secondaryKeywords: ['animated study background', 'lofi gif background', 'anime gif workspace'],
    estimatedSearchVolume: 'medium',
    priority: 9,
  },
  {
    slug: 'dark-aesthetic-study-setup',
    title: 'Dark Aesthetic Study Room Setup: Moody, Productive, Beautiful',
    category: 'Anime Study Setups',
    primaryKeyword: 'dark aesthetic study setup',
    secondaryKeywords: ['dark study room', 'dark academia aesthetic', 'moody study space'],
    estimatedSearchVolume: 'medium',
    priority: 10,
  },
]
